CREATE TABLE GA4_session (
  session_id VARCHAR(255) NOT NULL PRIMARY KEY,
  visitor_id VARCHAR(255) NOT NULL,
  user_id VARCHAR(255),
  visit_start_time INT NOT NULL,
  visit_start_time2 TIME NOT NULL,
  visit_start_date DATE NOT NULL,
  visit_start_datetime DATETIME NOT NULL,
  property_id VARCHAR(255) NOT NULL,
  brand VARCHAR(255) NOT NULL,
  market_code VARCHAR(255) NOT NULL,
  GA_client_id VARCHAR(255),
  session_number INT NOT NULL,
  visit_id INT NOT NULL,
  source VARCHAR(255),
  medium VARCHAR(255),
  campaign VARCHAR(255),
  ad_content VARCHAR(255),
  keyword VARCHAR(255),
  referrer VARCHAR(255),
  browser VARCHAR(255),
  device_category VARCHAR(255),
  language VARCHAR(255),
  bounced_session INT,
  got_interaction_event INT,
  returning_visitor INT,
  total_hits INT,
  total_page_views INT,
  time_on_site_seconds INT,
  event_start_date DATE NOT NULL,
  channel_grouping VARCHAR(255)
);


CREATE TABLE GA4_hit (
  hit_id                 VARCHAR(255) NOT NULL,
  hit_type               VARCHAR(255) NOT NULL,
  session_id             VARCHAR(255) NOT NULL,
  hit_number             INT NOT NULL,
  visitor_id             VARCHAR(255) NOT NULL,
  user_id                VARCHAR(255),
  visit_start_time       INT NOT NULL,
  visit_start_time2      TIME NOT NULL,
  visit_start_date       DATE NOT NULL,
  -- Duplicate name below; consider renaming to visit_start_datetime:
  visit_start_date       DATETIME NOT NULL,
  hit_datetime           DATETIME NOT NULL,
  hit_time               TIME NOT NULL,
  property_id            VARCHAR(255) NOT NULL,
  brand                  VARCHAR(255) NOT NULL,
  market_code            VARCHAR(255) NOT NULL,
  time                   INT,
  entrance               INT,
  exit                   INT,
  interaction            INT,
  referrer               VARCHAR(255),
  page_path              VARCHAR(255),
  host_name              VARCHAR(255),
  page_title             VARCHAR(255),
  event_name             VARCHAR(255),
  event_category         VARCHAR(255),
  event_action           VARCHAR(255),
  event_label            VARCHAR(255),
  event_value            INT,
  geo_continent          VARCHAR(255),
  geo_country            VARCHAR(255),
  geo_city               VARCHAR(255),
  geo_metro              VARCHAR(255),
  geo_region             VARCHAR(255),
  content_group_1        VARCHAR(255),
  content_group_2        VARCHAR(255),
  content_group_3        VARCHAR(255),
  content_group_4        VARCHAR(255),
  content_group_5        VARCHAR(255),
  previous_content_group_1 VARCHAR(255),
  previous_content_group_2 VARCHAR(255),
  previous_content_group_3 VARCHAR(255),
  previous_content_group_4 VARCHAR(255),
  previous_content_group_5 VARCHAR(255),
  event_start_date       DATE NOT NULL,
  PRIMARY KEY (hit_id)
);
