version: '3.8'

services:
  nl2sql:
    build: .
    container_name: nl2sql_app
    env_file:
      - .env
    volumes:
      - .:/app/nl2sql
    ports:
      - "8000:8000"
    command: uvicorn source.main:app --host 0.0.0.0 --port 8000 --reload
